### ISSUE TITLE
Error when updating angular to 5.0.1

### ISSUE THREAD

**Issue by fretje** [aspnetboilerplate/abp-ng2-module#15]
I updated an existing project using abp-ng2-module to Angular 5.0.1 today. After removing the node_modules folder, doing a yarn cache clean and then a yarn install again, I get an error when trying to build the project:

> WARNING in ./node_modules/abp-ng2-module/node_modules/@angular/core/@angular/core.es5.js
5659:15-36 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (C:\Projects\solartouch\SolarWeb\angular\node_modules\webpack\lib\dependencies\ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (C:\Projects\solartouch\SolarWeb\angular\node_modules\webpack\lib\Compilation.js:703:24)
    at Compilation.finish (C:\Projects\solartouch\SolarWeb\angular\node_modules\webpack\lib\Compilation.js:561:9)
    at applyPluginsParallel.err (C:\Projects\solartouch\SolarWeb\angular\node_modules\webpack\lib\Compiler.js:506:17)
    at C:\Projects\solartouch\SolarWeb\angular\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (C:\Projects\solartouch\SolarWeb\angular\node_modules\webpack\lib\Compilation.js:507:11)
    at processModuleDependencies.err (C:\Projects\solartouch\SolarWeb\angular\node_modules\webpack\lib\Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
 @ ./node_modules/abp-ng2-module/node_modules/@angular/core/@angular/core.es5.js
 @ ./node_modules/abp-ng2-module/src/multi-tenancy/abp-multi-tenancy.service.ts
 @ ./src/shared/session/app-session.service.ts
 @ ./src/root.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 webpack/hot/dev-server ./src/main.ts

It probably has something to do with the abp-ng2-module referenicng an older version of angular as it is accessing code under the node_modules folder under the abp-ng2-module folder.

After I manually delete the node_modules folder under the abp-ng2-modules folder, everything builds and runs fine. This is a temporary fix at best though...

Not sure what has to be changed here to mitigate that problem though...

**Comment by nevmeehan** [comment]
Exact same problem here.

**Comment by hikalkan** [comment]
We will upgrade to Angular 5.0 soon.

**Comment by nevmeehan** [comment]
Beautiful - that fixed it. Many Thanks.
