### ISSUE TITLE
Module build error Angular6 :-  missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property

### ISSUE THREAD

**Issue by ezra2310** [aspnetboilerplate/abp-ng2-module#33]
Hi All,
I have asp zero boilerplate. Im update all abp package but still gettingthe error.
**After update angular v4.4 to 6 then getting the below while run 'ng build'**

> ERROR in ./node_modules/abp-ng2-module/src/abp-user-configuration.service.ts
> Module build failed: Error: F:\Project\SourceCode\AlphaPhe\3\aspnet-core\src\AnkaaConsulting.APhe.Web.Host\node_modules\abp-ng2-module\src\abp-user-configuration.service.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
> The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
>     at AngularCompilerPlugin.getCompiledFile (F:\Project\SourceCode\AlphaPhe\3\aspnet-core\src\AnkaaConsulting.APhe.Web.Host\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:709:23)
>     at plugin.done.then (F:\Project\SourceCode\AlphaPhe\3\aspnet-core\src\AnkaaConsulting.APhe.Web.Host\node_modules\@ngtools\webpack\src\loader.js:41:31)
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:188:7)

Anybody got this issue. please help!!!

**Comment by pantonis** [comment]
Having the same problem with different file:
```
node_modules\abp-ng2-module\src\auth\permission-checker.service.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
```

**Comment by ezra2310** [comment]
@pantonis . Yes. Now application build added the below line in  tsconfig.json ,
"@abp/*": [ "../node_modules/abp-ng2-module/dist/src/*" ]

But could not able to login. login exception coming !!!

**Comment by pantonis** [comment]
@ezra2310 Which tsconfig.json file. Can you point to the path of the tsconfig.json please?

**Comment by ezra2310** [comment]
@pantonis  Host/Src/ tsconfig.json .  Inside SRC folder

**Comment by pantonis** [comment]
@ezra2310 strange I have that line and still does not work.
Can you post your full tsconfig.json please?

**Comment by ezra2310** [comment]
src/tsconfing.json
------------------------------------
{
  "compilerOptions": {
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [ "es6", "dom" ],
    "mapRoot": "./",
    "module": "es6",
    "skipLibCheck": true,
    "moduleResolution": "node",
    "outDir": "../dist/out-tsc",
    "sourceMap": true,
    "target": "es5",
    "typeRoots": [
      "../node_modules/@types"
    ],
    "baseUrl": ".",
    "paths": {
      "@abp/*": [ "../node_modules/abp-ng2-module/src/*" ],
      "@app/*": [ "./app/*" ],
      "@shared/*": [ "./shared/*" ],
      "@node_modules/*": [ "../node_modules/*" ],
      "@angular/*": [ "../node_modules/@angular/*" ]
    }
  },
  "exclude": [ "node_modules" ]
}

**Comment by pantonis** [comment]
Thanks for posting it. That didn't work it created hundreds of error.
Can you also post package.json and output of ng-v please?

**Comment by ezra2310** [comment]
Package.json
-------------------------
{
  "name": "abp-zero-template",
  "version": "4.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "ng": "ng",
    "start": "ng serve --host 0.0.0.0 --port 4200",
    "hmr": "ng serve --host 0.0.0.0 --port 4200 4201 --hmr -e=hmr",
    "test": "ng test",
    "pree2e": "webdriver-manager update --standalone false --gecko false",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular-redux/store": "^9.0.0",
    "@angular/animations": "6.0.6",
    "@angular/common": "6.0.6",
    "@angular/compiler": "6.0.6",
    "@angular/core": "6.0.6",
    "@angular/forms": "6.0.6",
    "@angular/http": "6.0.6",
    "@angular/platform-browser": "6.0.6",
    "@angular/platform-browser-dynamic": "6.0.6",
    "@angular/router": "6.0.6",
    "abp-ng2-module": "^3.0.0",
    "abp-web-resources": "^3.7.0",
    "angular-tree-component": "^5.1.2",
    "angular2-counto": "^1.2.3",
    "block-ui": "^2.70.1",
    "bootstrap": "^3.3.7",
    "bootstrap-daterangepicker": "^2.1.25",
    "bootstrap-select": "^1.12.2",
    "bootstrap-switch": "^3.3.4",
    "codelyzer": "^3.2.1",
    "core-js": "^2.4.1",
    "datamaps": "^0.5.8",
    "electron-to-chromium": "^1.3.50",
    "eonasdan-bootstrap-datetimepicker": "^4.17.47",
    "famfamfam-flags": "^1.0.0",
    "flot": "^0.8.0-alpha",
    "font-awesome": "^4.7.0",
    "jasmine-spec-reporter": "^3.3.0",
    "jquery": "^3.1.1",
    "jquery-migrate": "^3.0.0",
    "jquery-slimscroll": "^1.3.8",
    "jquery-sparkline": "^2.4.0",
    "jquery.flot.tooltip": "^0.9.0",
    "jquery.inputmask": "^3.3.4",
    "jquery.uniform": "^4.2.0",
    "jqueryui": "^1.11.1",
    "js-cookie": "^2.1.4",
    "jstree": "^3.3.4",
    "karma": "^1.6.0",
    "localforage": "^1.5.0",
    "lodash": "^4.17.4",
    "moment": "^2.18.1",
    "moment-timezone": "^0.5.13",
    "morris.js": "^0.5.0",
    "ng-recaptcha": "^3.0.0",
    "ng2-file-upload": "^1.2.1",
    "ng2modules-easypiechart": "^0.0.4",
    "ng2modules-flot": "^0.0.1",
    "ngx-bootstrap": "^1.9.3",
    "ngx-color-picker": "^4.0.3",
    "primeng": "4.2.1",
    "push.js": "1.0.4",
    "quill": "^1.3.0",
    "raphael": "^2.2.7",
    "rtl-detect": "^1.0.0",
    "rxjs": "^6.2.1",
    "rxjs-compat": "^6.2.1",
    "signalr": "^2.2.1",
    "simple-line-icons": "^2.4.1",
    "spin.js": "^2.3.2",
    "sweetalert": "^1.1.3",
    "tether": "^1.4.0",
    "timeago": "^1.6.1",
    "toastr": "^2.1.2",
    "ts-helpers": "^1.1.2",
    "ts-node": "~3.3.0",
    "typescript": "2.7.2",
    "waypoints": "^4.0.1",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.6.8",
    "@angular/cli": "6.0.8",
    "@angular/compiler-cli": "6.0.6",
    "@angularclass/hmr": "^2.1.3",
    "@angularclass/hmr-loader": "^3.0.4",
    "@types/bootstrap": "^3.3.33",
    "@types/grecaptcha": "^2.0.31",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/jquery": "^3.2.12",
    "@types/jquery.blockui": "0.0.28",
    "@types/jstree": "^3.3.34",
    "@types/lodash": "^4.14.62",
    "@types/moment": "^2.13.0",
    "@types/moment-timezone": "^0.2.34",
    "@types/morris.js": "^0.5.6",
    "@types/node": "^8.0.27",
    "@types/signalr": "^2.2.33",
    "@types/tether": "^1.4.2",
    "@types/toastr": "^2.1.33",
    "codelyzer": "~3.2.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "nswag": "11.12.10",
    "protractor": "~5.1.2",
    "ts-node": "~3.3.0",
    "tslint": "~5.7.0",
    "typescript": "2.7.2",
    "webpack-dev-middleware": "^3.1.3"
  }
}

ng -v
--------------------------

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 6.0.8
Node: 8.9.4
OS: win32 x64
Angular: 6.0.6
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cli                      6.0.8
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.1
typescript                        2.7.2
webpack                           4.8.3

**Comment by pantonis** [comment]
@ezra2310 Thanks for all the help. I managed to solve it by following instructions from @armory09 [here](https://github.com/aspnetboilerplate/abp-ng2-module/issues/27#issuecomment-402647816)

**Comment by ezra2310** [comment]
@ismcagdas  Yes. Close it. All working well. Thanks for support

**Comment by gnganpath** [comment]
For angular 6 with GoJS working project is here.
https://github.com/NorthwoodsSoftware/GoJS-projects/tree/master/angular-basic
It's working for me. Fun coding.
